pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {
        stage('Git Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('projects/my-jenkins-app') {
                    echo 'Building Application...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            when {
                expression { currentBuild.currentResult == 'SUCCESS' }
            }
            steps {
                dir('projects/my-jenkins-app') {
                    echo 'Running unit tests...'
                    sh 'mvn test'
                }
            }
        }

        stage('Code Review') {
            when {
                expression { currentBuild.currentResult == 'SUCCESS' }
            }
            steps {
                dir ('projects/my-jenkins-app') {
                    withSonarQubeEnv('SonarQube-Local'){
                sh 'mvn sonar:sonar'
            }
        }
    }
}
        
        stage ('Quality Gate'){
            steps {
                timeout (time: 5, unit:'MINUTES'){
                    waitforQualityGate abortpipeline: true
                }
            }
        }

        stage('Deploy') {
            when {
                expression { currentBuild.currentResult == 'SUCCESS' }
            }
            steps {
                echo 'Deploying Application...'
            }
        }
    }

    post {
        success {
            echo 'Pipeline COMPLETED successfully'
        }
        failure {
            echo 'Pipeline FAILED'
        }
    }
}
