pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Test AWS ECR Access') {
        steps {
         withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'aws-wagh'
        ]]) {
            sh '''
                aws sts get-caller-identity
                aws ecr describe-repositories \
                  --repository-names devops-dashboard \
                  --region ap-south-1
            '''
        }
    }
}
        stage('Create Virtual Environment') {
            steps {
                dir('projects/aws-devops-cicd') {
                    sh 'python3 -m venv venv'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('projects/aws-devops-cicd') {
                    sh 'venv/bin/python -m pip install --upgrade pip'
                    sh 'venv/bin/python -m pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('projects/aws-devops-cicd') {
                    sh 'venv/bin/python -m pytest'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('projects/aws-devops-cicd') {
                    sh 'docker build -t devops-dashboard:ci .'
                }
            }
        }
    }
}